---

- hosts: all
  become: yes
  vars_files:
    - vars/influxdb.yml
    - vars/secure_influxdb.yml
    - vars/grafana.yml

  roles:
  - role: update_upgrade
  - role: secure_server
  - role: hostname
  - role: mtchavez.influxdb
  - role: secure_influxdb
  - role: Stouts.grafana

