---

- hosts: all
  become: yes
  vars_files:
    - vars/influxdb.yml
    - vars/secure_influxdb.yml
    - vars/grafana.yml
    - vars/telegraf.yml
    - vars/secure_grafana.yml

  roles:
  - role: update_upgrade
  - role: secure_server
  - role: hostname
  - role: mtchavez.influxdb
  - role: secure_influxdb
  - role: remove_grafana # otherwise Stouts.grafana will have version trouble
  - role: Stouts.grafana
  - role: dj-wasabi.telegraf
  - role: secure_grafana

