version: '2'
services:
  couchdb:
    image: klaemo/couchdb:1.6.1
    ports:
      - 5984:5984 # for debugging for now, turn off in prod
    #environment:
    #  - COUCHDB_USER=admin
    #  - COUCHDB_PASSWORD=c57c92c3-2c51-456f-9ee6-da3ea90b1e8f # Change in production
  dashboard1:
    image: thomastoye/speelplein-cloud-dashboard:latest
    depends_on:
      - couchdb
    ports:
      - 8080:9000
    environment:
      - DASHBOARD_DB_NAME=ic-despeelberg
      - DASHBOARD_DB_HOST=couchdb
      - DASHBOARD_DB_PORT=5984
      - DASHBOARD_DB_HTTPS=false
      #- DASHBOARD_DB_USER=admin
      #- DASHBOARD_DB_PASS=c57c92c3-2c51-456f-9ee6-da3ea90b1e8f
      - DASHBOARD_SECRET
      - DASHBOARD_REMOTE_DB_PORT
      - DASHBOARD_REMOTE_DB_HOST
      - DASHBOARD_REMOTE_DB_USER
      - DASHBOARD_REMOTE_DB_PASS
      - DASHBOARD_AUTH0_CLIENT_ID
      - DASHBOARD_AUTH0_CLIENT_SECRET
      - DASHBOARD_AUTH0_AUDIENCE
  dashboard-frontend:
    image: thomastoye/inschrijven-cloud-dashboard-frontend:latest
    ports:
      - 80:80

