version: '2'
services:
  couchdb:
    image: klaemo/couchdb:1.6.1
    ports:
      - 5984:5984 # for debugging for now, turn off in prod
    #environment:
    #  - COUCHDB_USER=admin
    #  - COUCHDB_PASSWORD=c57c92c3-2c51-456f-9ee6-da3ea90b1e8f # Change in production
  admin_panel:
    image: thomastoye/speelsysteem-admin-panel:latest
    depends_on:
      - couchdb
    ports:
      - 9000:9000
    environment:
      # example for Cloudant: host = $USER.cloudant.com, user and pass set, port = 443, https = true
      - ADMIN_PANEL_SECRET
      - ADMIN_PANEL_DB_HOST=couchdb
      - ADMIN_PANEL_DB_PORT=5984
      - ADMIN_PANEL_DB_HTTPS=false
      #- ADMIN_PANEL_DB_USER=admin
      #- ADMIN_PANEL_DB_PASS=c57c92c3-2c51-456f-9ee6-da3ea90b1e8f
      - ADMIN_PANEL_REMOTE_DB_USER
      - ADMIN_PANEL_REMOTE_DB_PASS
      - ADMIN_PANEL_REMOTE_DB_HOST
      - ADMIN_PANEL_REMOTE_DB_PORT=443
      - ADMIN_PANEL_REMOTE_DB_HTTPS=true
  dashboard1:
    image: thomastoye/speelsysteem-dashboard:latest
    depends_on:
      - couchdb
    ports:
      - 8080:9000
    environment:
      - DASHBOARD_DB_NAME=ic-despeelberg
      - DASHBOARD_DB_HOST=couchdb
      - DASHBOARD_DB_PORT=5984
      - DASHBOARD_DB_HTTPS=false
      #- DASHBOARD_DB_USER=admin
      #- DASHBOARD_DB_PASS=c57c92c3-2c51-456f-9ee6-da3ea90b1e8f
      - DASHBOARD_SECRET
  dashboard-frontend:
    image: thomastoye/speelsysteem-dashboard-frontend:latest
    ports:
      - 80:80

