---

- name: Disable InfluxDB authentication
  lineinfile: dest=/etc/influxdb/influxdb.conf regexp="^  auth-enabled =" line="  auth-enabled = false"

- name: Restart InfluxDB service
  service: name=influxdb state=restarted

- name: Allow InfluxDB some time to restart
  pause: seconds=1

- name: Drop admin, grafana and telegraf users
  command: /usr/bin/influx -execute "DROP USER {{ item }}"
  with_items:
    - "{{ secure_influxdb_admin_user }}"
    - "{{ secure_influxdb_telegraf_user }}"
    - "{{ secure_influxdb_grafana_user }}"
  ignore_errors: yes

- name: Create InfluxDB admin user
  command: /usr/bin/influx -execute "CREATE USER {{ secure_influxdb_admin_user }} WITH PASSWORD '{{ secure_influxdb_admin_pass }}'"

- name: Create telegraf database
  command: /usr/bin/influx -execute "CREATE DATABASE telegraf"

- name: Create InfluxDB telegraf user
  command: /usr/bin/influx -execute "CREATE USER {{ secure_influxdb_telegraf_user }} WITH PASSWORD '{{ secure_influxdb_telegraf_pass }}'"

- name: Create InfluxDB Grafana user
  command: /usr/bin/influx -execute "CREATE USER {{ secure_influxdb_grafana_user }} WITH PASSWORD '{{ secure_influxdb_grafana_pass }}'"

- name: Grant write privileges on telegraf database to telegraf user
  command: /usr/bin/influx -execute "GRANT WRITE ON telegraf TO telegraf"

- name: Make grafana user admin
  command: /usr/bin/influx -execute "GRANT ALL PRIVILEGES TO grafana"

- name: Enable InfluxDB authentication
  lineinfile: dest=/etc/influxdb/influxdb.conf regexp="^  auth-enabled =" line="  auth-enabled = true"

- name: Restart InfluxDB service
  service: name=influxdb state=restarted

